### ISSUE TITLE
SOLID POD: Release 0.6.0

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#216]
- [x] Test initialisation
- [x] Test everything
- [x] Test with a few apps
- [ ] Anything else????

**Comment by anushkavidanage** [comment]
## Up for discussion
- Security key: do we need this per app or per POD? Or do we allow user to decide that? If we allow user to decide that then how do we structure app content?
- Logout before initialisation: If the user logs out before initialisation, we do not currently redirect to the login page. In order to do that we need to have a separate parameter for SolidLogin() to input the page to redirect after login.
- Ontology schema: We (Dawei, Sergio and Anushka) had initial discussions about the ontology/schema aspects of data we currently store in PODs. However, we have not incorporated this framework into our current development. Should we try to redesign our schema to the new version before release?
