### ISSUE TITLE
INITIALIZE POD: Move logout to CANCEL button next to but after SUBMIT

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#67]
## Description

While I am in the InitialisePod() page, is tehre a way to cancel out and return to the Login page (for SolidLogin) or return to the App page (for SolidLoginPopup)?

**Comment by junhaow1** [comment]
demo: 

https://github.com/anusii/solidpod/assets/37771259/20957c1f-0aa2-4cf3-8c1b-0e200f5202cd

**Comment by junhaow1** [comment]
https://github.com/anusii/keypod/pull/53 PR created

**Comment by junhaow1** [comment]
![Image](https://github.com/anusii/solidpod/assets/37771259/1a887d43-e500-44e7-a01d-2ff62fd1afe8)

will fix here , logout button backgound colour

**Comment by junhaow1** [comment]
to change initialisePod widget, not keypod (continue) page

**Comment by junhaow1** [comment]
This returns to the app rather than to the login screen. Thinking of the use case perhaps that is the right thing - I want to cancel out of the login attempt. 

- [ ] SolidLogin + `required: False` then replace back arrow with `SKIP` or even a forward arrow?
- [ ] SolidLogin and `required: True` the back should go to the Login page of the app
- [ ] SolidLoginPopup  back to the app, as is now

**Comment by gjwgit** [comment]
![Image](https://github.com/anusii/solidpod/assets/1681429/668bbb95-f5cb-496b-8f2b-25e507061a21)

**Comment by cdawei** [comment]
The pull request for this issue was merged a few months ago, shall we close this issue?

**Comment by junhaow1** [comment]
> The pull request for this issue was merged a few months ago, shall we close this issue?

Sounds good
